# Created by Waren Gonzaga with the help of project contributors.
# GitHub Sponsors: https://github.com/sponsors/warengonzaga
# Buy Me A Coffee: https://buymeacoffee.com/warengonzaga

github: warengonzaga
custom: https://buymeacoffee.com/warengonzaga

# Sponsoring this project means a lot to me. 
# Your support helps me to continue building great open-source projects just like this.